apiVersion: v1
kind: Service
metadata:
  name: np-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: app7
  ports:
  - port: 80
    targetPort: 80
