apiVersion: apps/v1
kind: Deployment
metadata:
  name: az-vol
spec:
  replicas: 2
  selector:
    matchLabels:
      app: az-vol
  template:
    metadata:
      labels:
        app: az-vol
    spec:
      volumes:
      - name: vol1
        persistentVolumeClaim: 
          claimName: az-file-pvc
      containers:
      - name: az-vol
        image: nginx:latest
        volumeMounts:
        - name: vol1
          mountPath: "/mnt/data"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: az-app-svc
spec:
  # On AKS load-balancer type would map service to a public ip
  # use kubectl get svc az-app-svc to get 'external-ip'
  type: LoadBalancer
  selector:
    app: az-vol
  ports:
  - port: 80
    targetPort: 80