apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: app10
  serviceName: headless-svc
  replicas: 3
  template:
    metadata:
      labels:
        app: app10
    spec:
      containers:
      - name: myapp
        image: mahendrshinde/myweb:1
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: headless-svc
spec:
  selector:
    app: app10
  clusterIP: None  ########## Set ClusterIP to NONE ########
