apiVersion: v1
kind: Pod
metadata:
  name: mypod
  
spec:
  imagePullSecrets:
    - name: my-reg
  
  containers:
  - name: myapp
    image: mahendrashinde.azurecr.io/mysql-sample:sakila
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3306
