apiVersion: v1
kind: Secret
metadata:
  name: mysecret
data:
  ACCESS_TOKEN: MjNydHEyM3VyZ3EyaXUzcmd1MnFrdjN0dWt5d2czdHVyYXZ3anJ5Y3Rh
  AUTH_URL: aHR0cDovL21haGVuZHJhLmNvbS9hcGkvb2F1dGg=

---
apiVersion: v1
kind: Pod
metadata:
  name: secret-po
spec:
  containers:
  - name: c1
    image: nginx:alpine
    envFrom:
    - secretRef:
        name: mysecret
    resources:
      limits:
        cpu: 50m
        memory: 32Mi
    ports:
    - containerPort: 80



