apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: mahendrshinde/myweb:1
    resources:
      limits:
        memory: "32Mi"
        cpu: "100m"
      requests:
        memory: "16Mi"
        cpu: "10m"

    ports:
      - containerPort: 80
